### ISSUE TITLE
Project Launcher: feature list and ideas

### ISSUE THREAD

**Issue by atdiar** [atdiar/particleui#16]
A Terminal UI tool should be available for the ease of creation of new UI projects, step-by-step.
It should allow to configure a project depending on whether it is a web project, mobile, or TUI etc.
If a web project, it can either use CSR (client-side rendering), SSR (server-side rendering), SSG (static site generation).

The TUI state holds the project config and can be serialized into a file.

# Web Project
A new project is declared inside a folder (root).

./root 
./dev | ./bin

## CSR
The default project structure is scaffolded. The root folder also maps to a go workspace/module? (probably module)
At the root, we have the source files for the application, which includes the main function.
This source file can be compiled and the wasm executable and all other relevant assets (index.html, CSS, images, favicon, fonts, etc.) will be found in the ./prod/app subfolder.

The .dev/app subfolder holds the livereloadable application executable (wasm) but not the generated index.html wasm loader or an asset folder: the ./prod folder asset is used.
It should avoid serving the dev folder by mistake.
.dev/server hold the development server source that is run as soon as the project is launched. (use DNS to have vanity local URLs?)
It should serve ./dev/app locally and also monitor the wasm file for change (or the CSS, or the assets etc. but they are in the .prod folder). On change, it should issue a SSE(Server-Sent Event) to the browser so that it can reload).
It requires for the source files to be monitored, especially the go source file which should try to recompile on change (see fsnotify).

the ./prod/server folder holds a generic fileserver.

## SSR

If the project requires Server-Side Rendering, one of the build artifacts for the project will be a custom server that renders each project endpoint pages on demand.
It is created by compiling the project with the -server build tag.
It should be automatically done when calling `zui build` (wasm + server binary should be built)

Note: reminder that every TUI action should have a corresponding written command for additional scripting and headless environments.

(TBC)

## TODO

- [x] HMR support (file change monitoring, communication to frontend for reloading via Server-Sent Events)
- [x] CSR , SSR server binaries should be created from the main.go file (use build tags)
- [x] SSG support (HTML and CSS rendered files)
- [ ] Terminal UI default project
- [x] web default project needs to be more dynamic (display time)
- [x] Add template support for project initialization (gonew) ; think about module name rewrites
- [x] implement interactive mode for zui init
- [ ] implement graphical mode for zui init
- [x] #19
- [ ] Github pages support

**Comment by atdiar** [comment]
Release and tmp directories should be just under dist.

**Comment by atdiar** [comment]
Thinking about this instead:

```txt
project/
├── zui.config.json
├── src/
│   ├── main.go
│   └── assets/
└── dist/
    ├── tmp/          # All temporary files
    │   ├── client/
    │   │   ├── _root/
    │   │   └── {basepath}/
    │   └── server/
    │       ├── csr/
    │       ├── ssr/
    │       └── ssg/
    └── release/      # All release files
        ├── client/
        │   ├── _root/
        │   └── {basepath}/
        └── server/
            ├── csr/
            ├── ssr/
            └── ssg/
```
